
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x03r4\xa7\xef\x02Qp5MC\x15\xces\xdd\x84'
    
_lr_action_items = {'AND':([4,5,10,11,],[-5,9,-6,-7,]),'LPAR':([0,1,6,8,9,],[1,1,1,1,1,]),'RPAR':([2,4,5,7,10,11,12,13,],[-2,-5,-4,11,-6,-7,-1,-3,]),'TAG':([0,1,6,8,9,],[4,4,4,4,4,]),'NOT':([0,1,6,8,9,],[6,6,6,6,6,]),'OR':([2,4,5,10,11,13,],[8,-5,-4,-6,-7,-3,]),'$end':([2,3,4,5,10,11,12,13,],[-2,0,-5,-4,-6,-7,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,1,],[3,7,]),'term':([0,1,8,],[2,2,12,]),'factor':([0,1,6,8,9,],[5,5,10,5,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> term OR term','expr',3,'p_exp_or','grammar.py',30),
  ('expr -> term','expr',1,'p_exp_term','grammar.py',34),
  ('term -> factor AND factor','term',3,'p_term_and','grammar.py',38),
  ('term -> factor','term',1,'p_term_factor','grammar.py',42),
  ('factor -> TAG','factor',1,'p_factor_tag','grammar.py',46),
  ('factor -> NOT factor','factor',2,'p_not','grammar.py',50),
  ('factor -> LPAR expr RPAR','factor',3,'p_par','grammar.py',54),
]
